name: Catalog
definition:
  description: Display the product catalog and the items available to purchase. Allows extended search to find a specific item. Provide the ability for administrators to update catalogs and associated items.
  strategic_classification:
      domain: core
      business_model: revenue_generator
      evolution: commodity
  domain_role:
      name: gateway context
      description: Provide catalog item allowing Basket, Ordering and Payment contexts to properly work.
ubiquitous_language:
    selector: concrete class implementing '.*IAggregateRoot<.*>'
inbound_communication:
    commands:
        selector: class implementing '.*ICommand$'
        handler: 
            selector: class implementing '.*ICommandHandler<.*>$'
            link: T -> .*ICommandHandler<T>$
    collaborators:
        - name: WebApp
          selector: class named '.*Controller$'
    policies:
        - method_attribute_pattern: 'Fact'
    domain_events:
        selector: class implementing 'IDomainEvent'